package config

import (
	"fmt"
	"path"
	"slices"
	"strings"

	"github.com/invopop/jsonschema"
)

// GenerateDocs renders human-readable Markdown documentation for the config
// file from the same reflected schema used by GenerateSchema. Keeping both
// generators on one source of truth means the docs cannot drift from the schema.
func GenerateDocs() (string, error) {
	r := &jsonschema.Reflector{}
	_ = r.AddGoComments("github.com/abs/mysql-mcp", "./internal/config")
	schema := r.Reflect(&Config{})

	var b strings.Builder
	b.WriteString("# Configuration\n\n")
	b.WriteString("> This file is generated by `mysql-mcp gen-config-docs`. Do not edit by hand.\n\n")
	b.WriteString("`mysql-mcp` reads a JSON config file. By default it looks for ")
	b.WriteString("`$XDG_CONFIG_HOME/mysql-mcp/config.json` (falling back to the XDG search path); ")
	b.WriteString("override with `--config`.\n\n")
	b.WriteString("Secret-bearing fields (`password`, `dsn`, SSH credentials) support `${ENV_VAR}` expansion.\n\n")

	// Document definitions in a stable, reader-friendly order.
	order := []string{"Config", "HTTPConfig", "SourceConfig", "SSHConfig"}
	names := make([]string, 0, len(schema.Definitions))
	for name := range definitionsMap(schema) {
		names = append(names, name)
	}
	slices.SortFunc(names, func(a, c string) int {
		ia, ic := slices.Index(order, a), slices.Index(order, c)
		if ia < 0 {
			ia = len(order)
		}
		if ic < 0 {
			ic = len(order)
		}
		if ia != ic {
			return ia - ic
		}
		return strings.Compare(a, c)
	})

	for _, name := range names {
		def := schema.Definitions[name]
		writeDefinition(&b, name, def)
	}
	return b.String(), nil
}

func definitionsMap(schema *jsonschema.Schema) jsonschema.Definitions {
	return schema.Definitions
}

func writeDefinition(b *strings.Builder, name string, def *jsonschema.Schema) {
	fmt.Fprintf(b, "## %s\n\n", name)
	if def.Description != "" {
		fmt.Fprintf(b, "%s\n\n", def.Description)
	}
	if def.Properties == nil || def.Properties.Len() == 0 {
		return
	}
	required := make(map[string]bool, len(def.Required))
	for _, r := range def.Required {
		required[r] = true
	}
	b.WriteString("| Field | Type | Required | Description |\n")
	b.WriteString("|-------|------|----------|-------------|\n")
	for pair := def.Properties.Oldest(); pair != nil; pair = pair.Next() {
		key, prop := pair.Key, pair.Value
		req := ""
		if required[key] {
			req = "yes"
		}
		desc := strings.ReplaceAll(prop.Description, "\n", " ")
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", key, propType(prop), req, desc)
	}
	b.WriteString("\n")
}

// propType renders a schema's type for the docs table, resolving $ref names and
// array element types.
func propType(s *jsonschema.Schema) string {
	if s.Ref != "" {
		return refName(s.Ref)
	}
	if s.Type == "array" && s.Items != nil {
		return propType(s.Items) + "[]"
	}
	if s.Type == "object" && s.AdditionalProperties != nil {
		return "map of " + propType(s.AdditionalProperties)
	}
	if len(s.Enum) > 0 {
		parts := make([]string, len(s.Enum))
		for i, e := range s.Enum {
			parts[i] = fmt.Sprintf("`%v`", e)
		}
		return strings.Join(parts, " \\| ")
	}
	if s.Type != "" {
		return s.Type
	}
	return "any"
}

func refName(ref string) string {
	return path.Base(ref)
}
